#!/opt/anaconda/bin/python

import numpy as np
import pandas as pd
import sys
import os

if not len(sys.argv) == 2:
   sys.stderr.write("incorrect number of arguments\n")
   exit(-1)

fname = sys.argv[1]

if not os.path.isfile(fname):
   sys.stderr.write("file does not exist\n")
   exit(-1)

try:
   d = pd.read_csv(fname, header=None)
   for i in d[9]:
      a = int(i)
except Exception, e:
   sys.stderr.write("Error "+str(e)+"\n")
   exit(-1)

print np.mean(d[9])
